name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '22'

    - name: Set environment variables
      run: |
        echo "URL=${{ secrets.URL }}" >> $GITHUB_ENV 
        echo "USER=${{ secrets.USER }}" >> $GITHUB_ENV
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run tests
      run: npx playwright test
